<a href="https://colab.research.google.com/github/srushti-03/ML_2024_ProjectNo9_Syntellect/blob/main/MICE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install scikit-learn


Example of MICE algorithm on a small dataset.

In [2]:
import numpy as np
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

# Generate sample data with missing values
np.random.seed(0)
n_samples, n_features = 10, 5
X_train = np.random.randn(n_samples, n_features)
y_train = np.random.randn(n_samples)
missing_mask = np.random.rand(n_samples, n_features) < 0.1
X_train_missing = X_train.copy()
X_train_missing[missing_mask] = np.nan

# Initialize the IterativeImputer
imputer = IterativeImputer(random_state=0)

# Fit the imputer model on the training data
imputer.fit(X_train_missing)

# Impute missing values
X_train_imputed = imputer.transform(X_train_missing)

# Output the imputed data
print("Original Data:")
print(X_train)
print("\nData with Missing Values:")
print(X_train_missing)
print("\nImputed Data:")
print(X_train_imputed)


Original Data:
[[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799]
 [-0.97727788  0.95008842 -0.15135721 -0.10321885  0.4105985 ]
 [ 0.14404357  1.45427351  0.76103773  0.12167502  0.44386323]
 [ 0.33367433  1.49407907 -0.20515826  0.3130677  -0.85409574]
 [-2.55298982  0.6536186   0.8644362  -0.74216502  2.26975462]
 [-1.45436567  0.04575852 -0.18718385  1.53277921  1.46935877]
 [ 0.15494743  0.37816252 -0.88778575 -1.98079647 -0.34791215]
 [ 0.15634897  1.23029068  1.20237985 -0.38732682 -0.30230275]
 [-1.04855297 -1.42001794 -1.70627019  1.9507754  -0.50965218]
 [-0.4380743  -1.25279536  0.77749036 -1.61389785 -0.21274028]]

Data with Missing Values:
[[ 1.76405235  0.40015721  0.97873798  2.2408932          nan]
 [-0.97727788  0.95008842 -0.15135721 -0.10321885         nan]
 [ 0.14404357  1.45427351  0.76103773  0.12167502  0.44386323]
 [ 0.33367433  1.49407907 -0.20515826  0.3130677          nan]
 [-2.55298982         nan  0.8644362  -0.74216502  2.26975462]
 [-1.4543656